name: Checkout Action Demo
on: 
  workflow_dispatch:
  push:
jobs:
  job1:
      runs-on: ubuntu-latest
      steps:
      - name: clone
        uses: actions/checkout@v7
        with:
          repository: ajnaidu/sample
      - name: build
        run: mvn clean install
      - name: deploy 
        run: echo "deploying the project..."
