name: multiplejobs workflow
on: 
  workflow_dispatch:
  push:
jobs:
  job1:
      runs-on: ubuntu-latest
      steps:
      - name: clone
        run: echo "cloning the project..."
      - name: build
        run: echo "building the project..."
      - name: deploy 
        run: echo "deploying the project..."
